### ISSUE TITLE
parlatype is broken with current debian testing

### ISSUE THREAD

**Issue by kpa-microdoc** [gkarsay/parlatype#100]
### Installation and version
debian testing

ii  gstreamer1.0-plugins-good:amd64 1.20.3-1     amd64        GStreamer plugins from the "good" set
ii  libc6:amd64                     2.35-3       amd64        GNU C Library: Shared libraries
ii  libglib2.0-0:amd64              2.74.0-3     amd64        GLib library of C routines
ii  libgtk-3-0:amd64                3.24.34-3    amd64        GTK graphical user interface library
ii  libparlatype5:amd64             3.1-2        amd64        Library for Parlatype - runtime version
ii  parlatype                       3.1-2        amd64        Minimal audio player for manual speech transcription

### Your desktop environment
KDE 
ii  kde-standard   5:129        amd64        KDE Plasma Desktop and standard set of applications

### Issue
parlatype crashes on startup

$ parlatype
**
GLib-GIO:ERROR:../../../gio/gdbusconnection.c:4287:invoke_get_property_in_idle_cb: assertion failed: (error != NULL)
Bail out! GLib-GIO:ERROR:../../../gio/gdbusconnection.c:4287:invoke_get_property_in_idle_cb: assertion failed: (error != NULL)

**Comment by kpa-microdoc** [comment]
Works again after glib update

**Comment by gkarsay** [comment]
I can reproduce it with even newer GLib. This seems to be a duplicate of #93.
