### ISSUE TITLE
Update flatpak platform, gnome/Platform//40 is EOL

### ISSUE THREAD

**Issue by prometoys** [gkarsay/parlatype#102]
When I run flatpak update, I got this warning:
```
Info: org.gnome.Platform//40 is end-of-life, with reason:
   The GNOME 40 runtime is no longer supported as of March 21, 2022. Please ask your application developer to migrate to a supported platform.
Applications using this runtime:
   org.parlatype.Parlatype
```
Please update platform to a recent Gnome version, if possible.

### Installation and version

org.parlatype.Parlatype from flatuhub, Version 3.1

### Your desktop environment

Ubuntu 20.04 LTS with GNOME

Btw. thanks for the great app. really helpfull

**Comment by gkarsay** [comment]
Done, however I had to drop support for Mozilla DeepSpeech.
Btw, things related to Flathub packaging actually belong to https://github.com/flathub/org.parlatype.Parlatype which has its own issue tracker.
