### ISSUE TITLE
./autogen.sh: 31:

### ISSUE THREAD

**Issue by 3P4R4** [gkarsay/parlatype#11]
en DEBIAN 

./autogen.sh: 31: ./autogen.sh: gtkdocize: not found

**Comment by gkarsay** [comment]
In Debian this should install all dependencies (see also README.md)
`sudo apt-get install build-essential automake autoconf intltool libgirepository1.0-dev libgladeui-dev gtk-doc-tools yelp-tools libgtk-3-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev`

You are missing the package `gtk-doc-tools`.

**Comment by 3P4R4** [comment]
Gracias muy amable y asombrado de la pronta respuesta...
