### ISSUE TITLE
Playback speed not displayed in version 4.0

### ISSUE THREAD

**Issue by driedtentacles** [gkarsay/parlatype#111]
### Installation and version

Installed Parlatype from flatpak from dl.flathub.org
Parlatype version is 4.0

### Your desktop environment

* Zorin OS 17 Core
* Gnome 41.7

### Issue

* Playback speed is not visible in the window. Still an issue no matter what size the window is.

### Other information

* Screenshot included:

![Screenshot from 2024-01-26 20-07-38](https://github.com/gkarsay/parlatype/assets/80104418/b39155fa-4690-477f-a999-d894d4e16094)

**Comment by gkarsay** [comment]
Thank you for spotting this regression!
