### ISSUE TITLE
Waveform not displayed on KDE/Plasma desktop

### ISSUE THREAD

**Issue by mherres55** [gkarsay/parlatype#12]
Both do not display the waveform.
Compiled on Fedora 25.

Any clues?

Thanks,

**Comment by gkarsay** [comment]
Thanks for your bug report! My guess is it's theme related.
1) Just to make sure: Did you use the latest git commit, the latest tar.gz (that is 1.5.1, released yesterday)? Output of `parlatype --version`should be parlatype 1.5.1.
2) Do you use GNOME or a different desktop environment?
3) Does it work with standard Adwaita theme?
4) If you use another theme, which one?

**Comment by mherres55** [comment]
1.5.1 version it is.
Using KDE desktop.  
I haven't switched any themes so whatever is default is what Ihave.

Thanks,

--/matt

**Comment by mherres55** [comment]
Any clues here might help:

bash-4.3# ldd /usr/bin/parlatype
        linux-vdso.so.1 (0x00007ffd8f4fd000)
        libparlatype.so.1 => /lib64/libparlatype.so.1 (0x00007f4f3d1cb000)
        libgstaudio-1.0.so.0 => /lib64/libgstaudio-1.0.so.0 (0x00007f4f3cf5b000)
        libgstbase-1.0.so.0 => /lib64/libgstbase-1.0.so.0 (0x00007f4f3ccf3000)
        libgstreamer-1.0.so.0 => /lib64/libgstreamer-1.0.so.0 (0x00007f4f3c9bb000)
        libgtk-3.so.0 => /lib64/libgtk-3.so.0 (0x00007f4f3c0b3000)
        libgdk-3.so.0 => /lib64/libgdk-3.so.0 (0x00007f4f3bdbb000)
        libpangocairo-1.0.so.0 => /lib64/libpangocairo-1.0.so.0 (0x00007f4f3bbab000)
        libpango-1.0.so.0 => /lib64/libpango-1.0.so.0 (0x00007f4f3b95b000)
        libatk-1.0.so.0 => /lib64/libatk-1.0.so.0 (0x00007f4f3b733000)
        libcairo-gobject.so.2 => /lib64/libcairo-gobject.so.2 (0x00007f4f3b523000)
        libcairo.so.2 => /lib64/libcairo.so.2 (0x00007f4f3b1f3000)
        libgdk_pixbuf-2.0.so.0 => /lib64/libgdk_pixbuf-2.0.so.0 (0x00007f4f3afcb000)
        libgio-2.0.so.0 => /lib64/libgio-2.0.so.0 (0x00007f4f3ac33000)
        libgobject-2.0.so.0 => /lib64/libgobject-2.0.so.0 (0x00007f4f3a9db000)
        libgmodule-2.0.so.0 => /lib64/libgmodule-2.0.so.0 (0x00007f4f3a7d3000)
        libglib-2.0.so.0 => /lib64/libglib-2.0.so.0 (0x00007f4f3a4bb000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f4f3a29b000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f4f39ed3000)
        libgsttag-1.0.so.0 => /lib64/libgsttag-1.0.so.0 (0x00007f4f39c93000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f4f39983000)
        liborc-0.4.so.0 => /lib64/liborc-0.4.so.0 (0x00007f4f39703000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f4f394fb000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f4f392f3000)
        libX11.so.6 => /lib64/libX11.so.6 (0x00007f4f38fb3000)
        libXi.so.6 => /lib64/libXi.so.6 (0x00007f4f38da3000)
        libXfixes.so.3 => /lib64/libXfixes.so.3 (0x00007f4f38b9b000)
        libatk-bridge-2.0.so.0 => /lib64/libatk-bridge-2.0.so.0 (0x00007f4f3896b000)
        libepoxy.so.0 => /lib64/libepoxy.so.0 (0x00007f4f38663000)
        libpangoft2-1.0.so.0 => /lib64/libpangoft2-1.0.so.0 (0x00007f4f3844b000)
        libfontconfig.so.1 => /lib64/libfontconfig.so.1 (0x00007f4f38203000)
        libXinerama.so.1 => /lib64/libXinerama.so.1 (0x00007f4f37ffb000)
        libXrandr.so.2 => /lib64/libXrandr.so.2 (0x00007f4f37deb000)
        libXcursor.so.1 => /lib64/libXcursor.so.1 (0x00007f4f37bdb000)
        libXcomposite.so.1 => /lib64/libXcomposite.so.1 (0x00007f4f379d3000)
        libXdamage.so.1 => /lib64/libXdamage.so.1 (0x00007f4f377cb000)
        libxkbcommon.so.0 => /lib64/libxkbcommon.so.0 (0x00007f4f3758b000)
        libwayland-cursor.so.0 => /lib64/libwayland-cursor.so.0 (0x00007f4f37383000)
        libwayland-egl.so.1 => /lib64/libwayland-egl.so.1 (0x00007f4f3717b000)
        libwayland-client.so.0 => /lib64/libwayland-client.so.0 (0x00007f4f36f6b000)
        libXext.so.6 => /lib64/libXext.so.6 (0x00007f4f36d53000)
        libthai.so.0 => /lib64/libthai.so.0 (0x00007f4f36b43000)
        libgthread-2.0.so.0 => /lib64/libgthread-2.0.so.0 (0x00007f4f3693b000)
        libharfbuzz.so.0 => /lib64/libharfbuzz.so.0 (0x00007f4f366d3000)
        libfreetype.so.6 => /lib64/libfreetype.so.6 (0x00007f4f36423000)
        libpixman-1.so.0 => /lib64/libpixman-1.so.0 (0x00007f4f36173000)
        libEGL.so.1 => /lib64/libEGL.so.1 (0x00007f4f35f5b000)
        libpng16.so.16 => /lib64/libpng16.so.16 (0x00007f4f35d23000)
        libxcb-shm.so.0 => /lib64/libxcb-shm.so.0 (0x00007f4f35b1b000)
        libxcb.so.1 => /lib64/libxcb.so.1 (0x00007f4f358f3000)
        libxcb-render.so.0 => /lib64/libxcb-render.so.0 (0x00007f4f356e3000)
        libXrender.so.1 => /lib64/libXrender.so.1 (0x00007f4f354d3000)
        libz.so.1 => /lib64/libz.so.1 (0x00007f4f352bb000)
        libGL.so.1 => /lib64/libGL.so.1 (0x00007f4f35013000)
        libffi.so.6 => /lib64/libffi.so.6 (0x00007f4f34e0b000)
        libpcre.so.1 => /lib64/libpcre.so.1 (0x00007f4f34b93000)
        libselinux.so.1 => /lib64/libselinux.so.1 (0x00007f4f3496b000)
        libresolv.so.2 => /lib64/libresolv.so.2 (0x00007f4f3474b000)
        libmount.so.1 => /lib64/libmount.so.1 (0x00007f4f344fb000)
        /lib64/ld-linux-x86-64.so.2 (0x000055ffd200a000)
        libatspi.so.0 => /lib64/libatspi.so.0 (0x00007f4f342c3000)
        libdbus-1.so.3 => /lib64/libdbus-1.so.3 (0x00007f4f34073000)
        libexpat.so.1 => /lib64/libexpat.so.1 (0x00007f4f33e43000)
        libdatrie.so.1 => /lib64/libdatrie.so.1 (0x00007f4f33c3b000)
        libgraphite2.so.3 => /lib64/libgraphite2.so.3 (0x00007f4f33a0b000)
        libbz2.so.1 => /lib64/libbz2.so.1 (0x00007f4f337fb000)
        libGLdispatch.so.0 => /lib64/libGLdispatch.so.0 (0x00007f4f3352b000)
        libXau.so.6 => /lib64/libXau.so.6 (0x00007f4f33323000)
        libGLX.so.0 => /lib64/libGLX.so.0 (0x00007f4f330f3000)
        libblkid.so.1 => /lib64/libblkid.so.1 (0x00007f4f32eab000)
        libuuid.so.1 => /lib64/libuuid.so.1 (0x00007f4f32ca3000)
        libsystemd.so.0 => /lib64/libsystemd.so.0 (0x00007f4f32c13000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f4f329fb000)
        libcap.so.2 => /lib64/libcap.so.2 (0x00007f4f327f3000)
        liblzma.so.5 => /lib64/liblzma.so.5 (0x00007f4f325cb000)
        liblz4.so.1 => /lib64/liblz4.so.1 (0x00007f4f323b3000)
        libgcrypt.so.20 => /lib64/libgcrypt.so.20 (0x00007f4f320cb000)
        libgpg-error.so.0 => /lib64/libgpg-error.so.0 (0x00007f4f31eb3000)

**Comment by mherres55** [comment]
My error: I'm using LXDE and loving it.
Was using KDE but it had some issues.

**Comment by gkarsay** [comment]
It's not your error :) Could you please confirm that it's working with LXDE but not with KDE?

**Comment by mherres55** [comment]
Yes I'm using LXDE...  Can't try KDE...  Don't want to mess things up...
Got another box I can try it on...

On Jul 10, 2017 12:10 PM, "Gabor Karsay" <notifications@github.com> wrote:

It's not your error :) Could you please confirm that it's working with LXDE
but not with KDE?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/gkarsay/parlatype/issues/12#issuecomment-314172078>,
or mute
the thread

**Comment by mherres55** [comment]
More clues:

(parlatype:29433): GLib-GIO-CRITICAL **: g_dbus_proxy_get_name_owner: assertion 'G_IS_DBUS_PROXY (proxy)' failed

(parlatype:29433): GLib-WARNING **: GError set over the top of a previous GError or uninitialized memory.
This indicates a bug in someone's code. You must ensure an error is NULL before it's set.
The overwriting error message was: The name org.freedesktop.portal.Desktop is not owned
Failed to create proxy: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SettingsDaemon was not provided by any .service files

**Comment by gkarsay** [comment]
Confirmed with KDE/Plasma 5.8.7.1. on Debian unstable.

**Comment by gkarsay** [comment]
I believe this is fixed with the commit referenced above. Please reopen the issue if it's still not working for you.

**Comment by mherres55** [comment]
Thanks I'll try it tonight.

**Comment by mherres55** [comment]
Absolutely Great!   Thanks. All Fixed.
