### ISSUE TITLE
Linux Mint 18.1 64-Bit:  Your Gstreamer installation is missing a plug-in.

### ISSUE THREAD

**Issue by Rbagman** [gkarsay/parlatype#13]
I found and followed the instructions here:

https://www.fossmint.com/parlatype-a-audio-transcription-tool-for-linux/

>$ sudo add-apt-repository ppa:gabor-karsay/parlatype
>$ sudo apt-get update 
>$ sudo apt install parlatype

And got a plug-in missing error. I then followed these instructions:

https://github.com/gkarsay/parlatype

>$ sudo apt-get install libgtk-3-0 libgstreamer1.0-0 gstreamer1.0-plugins-good

When I try to play an MP3 the app says:

Your Gstreamer installation is missing a plug-in.

**Comment by gkarsay** [comment]
Support for MP3 is in the "ugly" set of Gstreamer plugins.
Install with
```
$ sudo apt-get install gstreamer1.0-plugins-ugly
```

**Comment by gkarsay** [comment]
Updated README in commit 190f236f6ba0de67eb1075048cf4b219b1631298.

**Comment by Rbagman** [comment]
Thanks!
