### ISSUE TITLE
Parlatype Function is not listed in LibreOffice

### ISSUE THREAD

**Issue by Rbagman** [gkarsay/parlatype#14]
I'm not seeing Parlatype in LibreOffice function pane.  

README.md/LibreOffice Helpers says "them", but the command posted copies only the "Parlatype.py" file. 

The zip folder contained:
>/home/mint/Downloads/parlatype-master/libreoffice/Parlatype.py.in

I tried renaming this 'Parlatype.py' and then

>sudo cp libreoffice/Parlatype.py /usr/lib/libreoffice/share/Scripts/python/

restarted LibreOffice, but still no Parlatype function.

**Comment by gkarsay** [comment]
It's only one file, `Parlatype.py`. If you configure the package, the file should be generated from `Parlatype.py.in` but renaming it should work, too.
Maybe you have to install another package like this:
```
$ sudo apt-get install libreoffice-script-provider-python
```
Does that help?

**Comment by gkarsay** [comment]
I can't reproduce this issue and I can't resolve it without your help. Please notice that I will close this issue after a few weeks or months of inactivity.

**Comment by Rbagman** [comment]
I'm out of space.
