### ISSUE TITLE
pitch changes when adjusting speed

### ISSUE THREAD

**Issue by gbe-grbl** [gkarsay/parlatype#15]
Last week, when lowering the speed, the pitch of the voice stayed the same. 
Today the pitch is lower when the speed is lower.
Not sure what causes the problem.

Parlatype version is 1.5.1

**Comment by gbe-grbl** [comment]
I also can't see the waveform on startup. Last week I could. 

I'm using a dark theme on KDE. When I change the colour scheme to default and back to the dark one while parlatype is open, the waveform is visible (white). I suspect it's automatically displayed in black on startup.

**Comment by gkarsay** [comment]
Thank you for your bug report! Could you please add some more information about your installation.
1) Did you install from git, from tarball, from a distro package?
2) If from git, please paste the output of `git log -1 --pretty=oneline`
3) What's your distro (name and version)?

The waveform not displayed would be a separate bug. If you installed from git master and still experience it, please file a separate bug. I hope it's issue #12 and already resolved.

**Comment by gkarsay** [comment]
I can't reproduce this issue and I can't resolve it without your help. Please notice that I will close this issue after a few weeks or months of inactivity.

**Comment by gbe-grbl** [comment]
I'm sorry. It took a while for me to get back.
I installed it via distro package. My distro is Ubuntu 14.04.5 LTS (trusty). As I said, with KDE.
Thanks for looking into this.

**Comment by gkarsay** [comment]
Confirmed on Ubuntu Trusty. This is currently broken with GStreamer 1.2, included in Ubuntu Trusty, but should work with newer releases including GStreamer 1.3. I still kind of support Ubuntu Trusty, so I will try to fix this.

**Comment by gkarsay** [comment]
This should be fixed now in master. The fix will be released with Parlatype 1.5.2.
