### ISSUE TITLE
No page called "libreoffice-helpers" in Help

### ISSUE THREAD

**Issue by laspic** [gkarsay/parlatype#2]
Here is a second issue : I don't have the page called "libreoffice-helpers" in "help:parlatype" (so, the link is broken on the page "Timestamps"). 

It's not really problematic for using Parlatype but, because you direct users on this page (in "README.md"), I thought it could be bad... So, I also must admit that I didn't manage to use these "Libreoffice-helpers". :-)

(1.4.1 version, installed from your PPA. under Ubuntu 14.04)

**Comment by gkarsay** [comment]
Did you install the package "parlatype-libreoffice-helpers", too? It's a separate package.

**Comment by laspic** [comment]
Oops. Absolutely no. I miss that. Very sorry. It's works well, now (the help issue, I mean. I haven't tested the feature itself).
