### ISSUE TITLE
Media Keys not working since GNOME 3.24

### ISSUE THREAD

**Issue by eldelacajita** [gkarsay/parlatype#20]
First, let me say I _love_ this app. It's one of those small but purposeful apps that make Gnome and Linux great!

I'm using Parlatype 1.5.1 from AUR in Arch Linux with Gnome 3.26.2. 

I can change the volume using the media keys from my keyboard, but the "pause/play" and the "back" and "forward" buttons don't work. I don't know if this is a bug or a missing feature, but if would be great if it worked that way. Having to reach for the mouse to pause/play kind of defeats the purpose. 

This is what shows up when hitting one of those three media buttons:
![captura de pantalla de 2017-11-06 22-56-05](https://user-images.githubusercontent.com/2880679/32466039-e4ed5e6e-c345-11e7-8472-8d0dbce8214a.png)

This is what I get when running from the terminal:

```
(parlatype:21730): Gtk-WARNING **: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
Failed to create proxy: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SettingsDaemon was not provided by any .service files
Failed to create proxy: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SettingsDaemon was not provided by any .service files
Failed to create proxy: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SettingsDaemon was not provided by any .service files

```
That shows at the beginning, and I get no further errors. I gess it's not relevant to the issue, but I'm using the Paper icon theme and the Pop GTK theme. 

This happens all the time, and I didn't test previous versions so I'm not sure this is a new issue or not.

**Comment by julianrichen** [comment]
On my install the media keys work. From the error message it would seem like you don't have `gnome-settings-daemon` installed, Parlatype use them, source: [1](https://github.com/gkarsay/parlatype/blob/v1.5.1/src/pt-mediakeys.h#L17), [2](https://github.com/gkarsay/parlatype/blob/v1.5.1/src/pt-mediakeys.c#L119).

 I think the AUR has it under `gnome-settings-daemon-ubuntu`? Strange considering you are using GNOME, it should be preinstalled.

**Comment by eldelacajita** [comment]
Let me check... When searching with yaourt, I get these options to install (and n.1 is installed): 

```
1 extra/gnome-settings-daemon 3.26.2-1 (gnome) [installed]
    GNOME Settings Daemon
2 aur/gnome-settings-daemon-120dpi 3.18.1-1 (Out of Date) (1) (0,00)
    The GNOME Settings daemon with an additional patch to change GNOME dpi 
    settings from 96 to 120 dpi.
3 aur/gnome-settings-daemon-compat 3.6.4-10 (5) (0,07)
    Compatibility package that provides the background, media keys and mount 
    helpers from GNOME Settings Daemon 3.6
4 aur/gnome-settings-daemon-elementary 3.22.1-1 (1) (0,07)
    GNOME Settings Daemon (with ElementaryOS patches)
5 aur/gnome-settings-daemon-shutdown 3.26.1-1 (1) (0,71)
    The GNOME Settings daemon with shutdown button action
6 aur/gnome-settings-daemon-ubuntu 3.22.1-1 (0) (0,00)
    GNOME Settings Daemon
7 aur/gnome-settings-daemon-volume-step-patch 3.24.3-1 (6) (0,02)
    GNOME Settings daemon with an additional patch to allow configuration of 
    volume steps
```
So I have ```gnome-settings-daemon``` installed from the extra repository in Antergos. Is ```gnome-settings-daemon-ubuntu``` different?

**Comment by gkarsay** [comment]
Thank you, I'm happy to hear you like Parlatype! At the moment I don't see more than it's a problem talking to gnome-settings-daemon. Do you have similar issues with other programs? Please try totem ("Videos") and "pause/play" button.

**Comment by eldelacajita** [comment]
They work great on any other app I've tried.

**Comment by gkarsay** [comment]
Confirmed, see https://bugzilla.gnome.org/show_bug.cgi?id=781326

**Comment by gkarsay** [comment]
This is a serious bug, I plan to make a release 1.5.3 within a week or so.

**Comment by eldelacajita** [comment]
Awesome!

**Comment by eldelacajita** [comment]
I just wanted to confirm: I'm using the new version and media keys work **perfectly**! Thank you! 😃

**Comment by amicalmant** [comment]
Hi @gkarsay ! I am running Parlatype v.1.5.6 provided by the Linux Mint 19 distribution and the keyboard controls work fine -- except the LibreOffice macros that trigger this error:

A scripting structure error occurred while running scriptvnd.sun.star.script:Parlatype.py$PlayPause?language=Python&location=share in Python.

Message : <class 'ImportError'>: No module named 'dbus'
  File "/opt/libreoffice6.1/program/pythonscript.py", line 1047, in getScript
    mod = self.provCtx.getModuleByUrl( fileUri )
  File "/opt/libreoffice6.1/program/pythonscript.py", line 484, in getModuleByUrl
    exec(code, entry.module.__dict__)
  File "/opt/libreoffice6.1/share/Scripts/python/Parlatype.py", line 22, in <module>
    import dbus
  File "/opt/libreoffice6.1/program/uno.py", line 347, in _uno_import
    return _builtin_import(name, *optargs, **kwargs)

Is it related and is there a way to fix this?

* Linux Mint 19
* LibreOffice 6.1.3.2
* Parlatype v.1.5.6
* gnome-settings-daemon (3.28.1-0ubuntu1.1) bionic
* dbus v1.12.2-1ubuntu1
* python-dbus v1.2.6-1
