### ISSUE TITLE
Location of menus and buttons

### ISSUE THREAD

**Issue by eldelacajita** [gkarsay/parlatype#22]
Hi! This is not a bug report but more like a discussion thread. I have been using and loving this app for a while, and would like to share some thoughts on how I think the interface could be improved. It is quite good already, but I feel like some buttons and options could be relocated to make the interface more compact and take advantage of the CSD headerbar. First, two questions:

1. Are there any plans regarding the interface?
2. Do you mind if I share some suggestions and try to do a couple of design mockups?

I ask this before even getting into detail because I know that apparently easy design changes can take a lot of development time and I don't want to propose something that was already considered, is on the works and/or would require too much work. But I would love to give it a try and at least have a discussion on what could be done or not.

**Comment by eldelacajita** [comment]
Ok, maybe part of this IS really a bug. I'm seeing both the "cog" menu and a regular menu, but in other screenshots there seems to be only a "cog" menu. 

What the main website shows:
![imagen](https://user-images.githubusercontent.com/2880679/33063189-0a7c9e76-cea2-11e7-86cb-2b73364035e8.png)

What I see: 
![imagen](https://user-images.githubusercontent.com/2880679/33063043-8d4c34b6-cea1-11e7-8e47-5e089652a110.png)

Is this intended, or just a bug? The double menu was one of the main things I thought could be improved.

**Comment by gkarsay** [comment]
I have no plans at the moment for the interface. Mockups are welcome but you could also describe what you think could be improved.

The traditional menu (in your screenshot Archivo, Editar, Ayuda) should not appear in GNOME. It appears in desktop environments that request it, like Xfce or Unity. In GNOME this is in the application menu in the upper left corner of the desktop next to Activities.

It might be theme dependent. My other guess is that you have changed the behaviour in gnome-tweak-tool. In tab "Top Bar" there is a switch for "Application Menu". This should toggle it (restart Parlatype after changing that setting).

**Comment by eldelacajita** [comment]
Yes, it was the "Show Application Menu" setting, thanks for pointing that out. I had it disabled because I prefer the AppMenu to show on the window headerbar as a button instead of on the top bar (which usually does work, but not in Parlatype). But I found a workaround so I can live with that.

This solves most of the "issues" I had with the interface. I was thinking about integrating both menus but that makes less sense now. So I have just a couple of ideas left:

* Putting "Open file" and "Recent files" in the cog menu instead. The appmenu is usually left for "Preferences", "About" and "Help", so I wasn't expecting those frequent actions to be there. In Gnome apps the "open file" action is usually a button on the headerbar, but I like the clean concept of just having the "play" button there, as it is now.
* Moving the "View follows cursor" toggle to the preferences dialog, as it's something I don't see myself changing a lot. Isn't it more like a _setting_? Or do people change this frequently?
* Turning the timestamp related actions into buttons in the bottom bar, as they are timeline-related and potentially more frequently used. I'm not sure about this one, though, as it would make the interface a bit more cluttered.

**Comment by gkarsay** [comment]
* Moving "Open file" and "Recent files" seems like a good idea. I'll consider it, but don't expect it soon.
* The "View follows cursor" is not a setting. You don't need it often, only when you start scrolling the view. Then you can return to the cursor's position with that. In an older version you could click on the time label to jump to that position but it was not obvious that you can click a label.
* I'm aware the timestamp actions are a bit akward to use and actually I don't use them myself from the menu. I have my shortcuts in LibreOffice. If you don't use that, it's easier to drag'n'drop: Drag the time label to an editor or drag from the editor on the waveview. Those menu items are a bit hidden because I'm not sure if they are really useful.

**Comment by eldelacajita** [comment]
Thanks, @gkarsay for your reply. In the same order:

- Great! No hurry, this is an improvement, not a killer bug.
- OK, so I misunderstood the function of that button. The description  "View follows cursor" made me think it was a one time setting or preference. It is more like a toggle, and the use you describe is even more like a one-time button than a toggle. I understand now that it's mostly linked to the scrolling action. I'll try that again and see how it works.
- I think you are right. That function is either used by shortcuts (if Parlatype is not visible) or by dragging (if Parlatype is visible on top). Actually, most of Parlatype natural workflow is shortcut driven, so the menu is just a fallback.

**Comment by gkarsay** [comment]
GNOME's design guidelines have changed, with GNOME 3.32 there will be no [application menu](https://developer.gnome.org/hig/stable/application-menus.html) shown anymore.

I will move everything to the [primary menu](https://developer.gnome.org/hig/stable/primary-menus.html), which will probably look like this:
```
Copy timestamp
Insert timestamp
Go to ...
--------
Open file
Open recent files
--------
Preferences
Keyboard shortcuts
Help
About Parlatype
```

The guidelines may still change a bit, I will wait to see what will be the common practice. Probably I will remove the alternative menu, which was originally intended for Unity (the traditional menu shown in the screenshot with dark theme above).

Probably "Open recent files" will be removed in the future because this was removed in GTK+ 4. The normal "Open file" dialog has something similar.

**Comment by eldelacajita** [comment]
Sounds good!

**Comment by gkarsay** [comment]
I encountered 2 problems with this. In our case the new primary menu will be in most cases bigger (in height) than the application window.
Due to https://gitlab.gnome.org/GNOME/gtk/issues/543 it won't be shown fully with X11, only on Wayland, if the window is smaller than the menu.
And due to https://gitlab.gnome.org/GNOME/gtk/issues/640 it might be shown partly offscreen.

**Comment by eldelacajita** [comment]
So the only solution to this would be making the menu shorter? 

That could be done by:
- Taking the timestamp actions out as timeline-related buttons, as we already discussed. 
- Splitting it into a second menu, like in the image below. This would make sense if the app had a split pane or sidebar, but it's not the case.

![gnome-app-menu-migration-proposal](https://user-images.githubusercontent.com/2880679/46654162-66890480-cba8-11e8-8f7f-e598320acc51.jpg)
(Image taken from [here](https://www.omgubuntu.co.uk/2018/06/gnome-app-menu-migration))

Both options would clutter the interface a bit, and only the first one would be adding something useful. The timestamp actions could also be turned into contextual right-click actions over the timeline, making them a bit less discoverable but keeping the interface clean. 

Have you thought of other ways to solve this?

**Comment by gkarsay** [comment]
This is what I came up with so far:

1) Implement the new GNOME design guidelines with all menu items in the primary menu and the "Info" item renamed to "About Parlatype".

![bildschirmfoto von 2018-10-11 18-44-55](https://user-images.githubusercontent.com/8670449/46820882-87f41700-cd87-11e8-84d9-2f3434dbc3ba.png)

This only works well, if the window has a vertical size like in the screenshot. The menu can be a little bit bigger than the window, just like the shadow. If the window is smaller and you are using X11, it might look like this:

![bildschirmfoto von 2018-10-11 18-46-15](https://user-images.githubusercontent.com/8670449/46821248-6e070400-cd88-11e8-8bca-c5b4367dbe86.png)

Under Wayland this problem doesn't show up, however, at certain sizes the menu is shown above the window. If the window is at the upper edge, then everything above is cut under Wayland, too.

![bildschirmfoto von 2018-10-11 18-46-40](https://user-images.githubusercontent.com/8670449/46821347-aeff1880-cd88-11e8-8120-c9e4c68156d0.png)

2) I added a secondary menu. I'm not really happy with it, but for now I think it's the best solution.

![bildschirmfoto von 2018-10-11 18-49-42](https://user-images.githubusercontent.com/8670449/46821403-d655e580-cd88-11e8-873f-ae0721dec54e.png)

The 3 items moved from primary to secondary menu.

![bildschirmfoto von 2018-10-11 18-49-37](https://user-images.githubusercontent.com/8670449/46821438-f38ab400-cd88-11e8-892a-641b54aad2e0.png)

3) I moved the "Play" button from the headerbar to the window where the other controls are.

![bildschirmfoto von 2018-10-11 18-51-15](https://user-images.githubusercontent.com/8670449/46821458-0d2bfb80-cd89-11e8-8a19-b0ff931b2ab3.png)

The "Open" button is always visible. It has the "suggested" color only at start up when there is no file loaded yet.

![bildschirmfoto von 2018-10-11 18-51-53](https://user-images.githubusercontent.com/8670449/46821501-203ecb80-cd89-11e8-9095-c0a0fbd41247.png)

I removed the open related items from the primary menu. Also the "Recent Files". There is no replacement for them for now. The standard open dialog has some recently used files, but for some reason they are showing different results and I'm not aware of a way to influence that.

![bildschirmfoto von 2018-10-11 18-52-00](https://user-images.githubusercontent.com/8670449/46821569-5d0ac280-cd89-11e8-8f9a-855892c40dac.png)

This is work in progress in a private branch and not on master yet. Feedback and suggestions are welcome!

**Comment by eldelacajita** [comment]
Looking good so far. The change in the play button makes sense to me, I like that one. 

I'm not convinced about the double menu, but seems to be an approach taken by other apps, and should minimize the issue for now. 

On the other hand, there may be another approach: to try to link the timestamp-related actions to the timestamp numbers.

I can imagine three ways:
1. The timestamp is inside a button, and when you click it, you get a popover with the options. A bit like the breadcrumbs in the Gnome Files pathbar, maybe.
2. The timestamp is shown inside an editable text field, so you can easily select, copy, paste or edit that text to move around the timeline. The "Go to..." dialog could be avoided with this approach.
3. A small button beside the timestamp. 

Here's a quick mockup of the first two options. Normal (bottom) and active (top).

![parlatype-timestamp-mockup](https://user-images.githubusercontent.com/2880679/46839166-dc65b980-cdbc-11e8-9c0e-b1c6cf399689.png)

This approach is probably a bit un-orthodox, but I like the easy interaction it could provide, especially the second one, which seems quite intuitive to me. No buttons, no menus, just direct edit/copy/paste.

**Comment by gkarsay** [comment]
Thanks for the suggestion, I like it very much and I wouldn't have had the idea myself. I'm now quite satisfied with the new solution which looks like this:

![bildschirmfoto vom 2018-10-12 16-43-04](https://user-images.githubusercontent.com/8670449/46876445-9ea97500-ce3e-11e8-8ee4-9fe808cb212c.png)

The "Go to cursor" button is now gone and a menu item in the popover. I changed the wording slightly and the "Go to time in clipboard" label shows now the time (if there's a timestamp in the clipboard).

**Comment by eldelacajita** [comment]
That was fast! :smile: 

I hadn't thought of including the "go to cursor" button inside, but it makes the interface even cleaner. And the "go to time..." line is perfect now. Good job! Looking forward to try it and see how it works hands-on.

**Comment by eldelacajita** [comment]
Hi, @gkarsay! Do you have any plans on when to release these changes (v 1.6)? I'm eager to try them :smile:

**Comment by gkarsay** [comment]
Well, I plan a release in March 2019. Obviously I'm a bit behind schedule. I'll try to release soon, probably with less testing I intended to :(

**Comment by eldelacajita** [comment]
Oh, no pressure! If that helps, I can try and compile it to test the latest version.
