### ISSUE TITLE
[feature request] Audio Bisect

### ISSUE THREAD

**Issue by ideasman42** [gkarsay/parlatype#23]
It would be useful to be able to bisect (like git bisect) - to lookup a time when you're not sure of the timestamp of them region of audio you last heard.

An example of how this could work:

- Press a key to activate bisect
- Start playing in the middle of the audio
- Press left/right to select a side
- ... iterate ...
- Enter to finish and stay at the current time OR Escape to cancel and return to the timestamp before starting bisect

**Comment by gkarsay** [comment]
Well, I think I don't fully understand your use case. Could you please elaborate a bit more on what you are exactly doing or what you want to achieve. Are you transcribing something, are you working with an editor or just want to find something?

Lets say you want to lookup a time, as you say. Lets assume you have found it. Why do you want to return then where you started from? If you're using an editor, you can save the starting timestamp and then return to it whenever you want. Or am I missing something?

**Comment by ideasman42** [comment]
The use case is you have listened to part of the audio, but you aren't sure where you are up to exactly.

Pressing Escape to back out of the change is just a quick way to back out of a bad bisect.

**Comment by gkarsay** [comment]
I'm sorry, this doesn't sound convincing to me.
