### ISSUE TITLE
Media keys only work as intended when starting from the terminal.

### ISSUE THREAD

**Issue by space-trash** [gkarsay/parlatype#29]
### Installation and version

Q. How did you install Parlatype?

* _A. Linux Mint Software Manager / Flatpak. The Parlatype version is 1.5.3_

### Your desktop environment

Q. What's your distro? 

* _A. Linux Mint 18.3_

Q. What's your desktop environment? (GNOME, KDE, XFCE ...)

* _A. Cinnamon_

### Issue

Q. What is not working as expected?

* _A. I was originally going to post the following issue :_

_« Play, Stop, Previous, and Next keys work in Rhythmbox and the other default media player in Linux Mint, but don't do anything in Parlatype. Spacebar works to toggle play/stop when focus is on Parlatype »._

_But as I went further down your checklist, I hit the « If you start Parlatype from terminal, is there any error output? » question, and when I tried it, starting Parlatype from the terminal actually solved the problem. All in all, if I run Parlatype from the Software Manager, the menu or the taskbar, the media keys don’t work as intended. But if I use the terminal to open Parlatype, then the media keys work as intended (and Spacebar stops working as a play/stop button, even when focus is on the parlatype window). Take note : if I quit Parlatype and close the terminal, and run Parlatype through other means (Software Manager, menu, taskbar…) then the media keys stop working as intended (and spacebar is back as a start/stop button._

Q. Does it happen all the time?

* _A. Only when I don’t start parlatype from the terminal._

Q. Did it work in the past (a regression)?

* _A. Yes, when I start parlatype from the terminal._

Q. What steps are needed to reproduce it?

* _A. Install Parlatype (Software Manager/Flatpak), launch it via Software Manager or taskbar/menu icons, load an mp3, notice that the media keys don’t work as intended, and that spacebar works as a play/stop button._

_Close Parlatype, open it from the terminal, load an mp3, notice that media keys work as intended (and spacebar is disabled as a play/stop button even when focus is on the Parlatype window)._

_Close Parlatype again, launch it via Software Manager or taskbar/menu icons, load an mp3, notice that the media keys don’t work anymore in Parlatype (and spacebar works again as a play/stop button)._

Q. If you start Parlatype from terminal, is there any error output?

* _A. No. Starting Parlatype from terminal actually solves the problem (though it underlines that starting Parlatype through other means than the terminal might cause an issue)._

### Other information

_I have a workaround (starting Parlatype from terminal), and I have no idea if it means there is an issue with Parlatype_ itself, _but I figured you might like to know about this, and I guess fixing it would make things a little more convenient, even for me (though typing "parlatype" in the terminal is a very minor inconvenience)._

**Comment by gkarsay** [comment]
Thank you for your report! Could you please confirm that it's the same version 1.5.3 if started from terminal. I remember from my first experiments with Flatpak that it was not always clear whether the Flatpak version is running or the system-wide installed instance (that might have a different version). Just check out the About/Info box.

**Comment by space-trash** [comment]
Indeed, starting from the terminal launches another version (1.5.4). Good catch!

Do note that while troubleshooting, I tried reinstalling from source as well (https://github.com/gkarsay/parlatype), so for some reason _both_ versions might coexist on my system. I did not know/think it was possible.

**Comment by gkarsay** [comment]
O.k., that means I'll have to upgrade the Flatpak version to 1.5.4. I thought it was not needed. 1.5.4 is basically just a fix for media keys on older systems (e.g. Linux Mint 18.3). I thought in Flatpak the bundled runtime was relevant, which should work fine, but obviously the media key system of the host is used. I will do that in the next days.

**Comment by gkarsay** [comment]
This should be fixed fixed with Flatpak version 1.5.4, the current is already 1.5.5. Please reopen if you still have this issue.

**Comment by axelmeunier** [comment]
Hi I just installed Flatpak version 2.0 on Ubuntu 19.10 and media keys do not work.
What shall i do to help debug ?

**Comment by axelmeunier** [comment]
> Hi I just installed Flatpak version 2.0 on Ubuntu 19.10 and media keys do not work.
> What shall i do to help debug ?

Forget about my comment : it seems media keys do not work at all by default on my machine in Ubuntu (I used previously Fedora and it worked OOB) so nothing to do with Parlatype. After mapping the keys correctly, it works indeed.

**Comment by gkarsay** [comment]
Thank you, I'm glad it works for you now.
