### ISSUE TITLE
No display of file and no forward - backward button

### ISSUE THREAD

**Issue by mart1oeil** [gkarsay/parlatype#30]
I installed an update of parlatype on my Ubuntu via ppa:gabor-karsay/parlatype and I can't see any display of the media anymore, neither forward and backward buttons. I just can use the play and pause button.

Package: parlatype
Priority: optional
Section: sound
Installed-Size: 770
Maintainer: Gabor Karsay <gabor.karsay@gmx.at>
Architecture: amd64
Version: 1.5.4-0ubuntu1~artful1
Depends: gstreamer1.0-plugins-good, libc6 (>= 2.7), libglib2.0-0 (>= 2.41.2), libgtk-3-0 (>= 3.21.4), libparlatype1 (>= 1.5), dconf-gsettings-backend | gsettings-backend
Filename: pool/main/p/parlatype/parlatype_1.5.4-0ubuntu1~artful1_amd64.deb

### Your desktop environment
Ubuntu 17.10
Gnome
Package: libreoffice
Architecture: amd64
Version: 1:5.4.1-0ubuntu1

### Issue
It was'nt the case before (don't know which version I used before)

* If you start Parlatype from terminal, is there any error output?
 Output when starting Parlatype and loading a file :
(parlatype:15194): Gtk-CRITICAL **: Error building template class 'PtWindow' for an instance of type 'PtWindow': .:3:2020 Invalid signal 'play-toggled' for type 'PtWaveviewer'

(parlatype:15194): GLib-GIO-CRITICAL **: g_settings_bind_with_mapping: assertion 'G_IS_OBJECT (object)' failed

(parlatype:15194): GLib-GIO-CRITICAL **: g_settings_bind_with_mapping: assertion 'G_IS_OBJECT (object)' failed

(parlatype:15194): GLib-GObject-CRITICAL **: g_object_bind_property_full: assertion 'G_IS_OBJECT (source)' failed

(parlatype:15194): Gtk-CRITICAL **: gtk_button_set_label: assertion 'GTK_IS_BUTTON (button)' failed

(parlatype:15194): Gtk-CRITICAL **: gtk_button_set_image: assertion 'GTK_IS_BUTTON (button)' failed

(parlatype:15194): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(parlatype:15194): GLib-GObject-CRITICAL **: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(parlatype:15194): GLib-GObject-CRITICAL **: g_object_bind_property_full: assertion 'G_IS_OBJECT (source)' failed

(parlatype:15194): Gtk-CRITICAL **: gtk_drag_source_set: assertion 'GTK_IS_WIDGET (widget)' failed

(parlatype:15194): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(parlatype:15194): GLib-GObject-CRITICAL **: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(parlatype:15194): Gtk-CRITICAL **: gtk_widget_set_sensitive: assertion 'GTK_IS_WIDGET (widget)' failed

(parlatype:15194): Gtk-CRITICAL **: gtk_widget_set_sensitive: assertion 'GTK_IS_WIDGET (widget)' failed

(parlatype:15194): Gtk-CRITICAL **: gtk_widget_set_sensitive: assertion 'GTK_IS_WIDGET (widget)' failed

(parlatype:15194): Gtk-CRITICAL **: gtk_widget_set_sensitive: assertion 'GTK_IS_WIDGET (widget)' failed

(parlatype:15194): Gtk-CRITICAL **: gtk_widget_set_sensitive: assertion 'GTK_IS_WIDGET (widget)' failed

(parlatype:15194): Gtk-CRITICAL **: gtk_label_set_text: assertion 'GTK_IS_LABEL (label)' failed

(parlatype:15194): Gtk-CRITICAL **: gtk_widget_set_tooltip_text: assertion 'GTK_IS_WIDGET (widget)' failed

(parlatype:15194): Gtk-CRITICAL **: gtk_widget_set_tooltip_text: assertion 'GTK_IS_WIDGET (widget)' failed

** (parlatype:15194): CRITICAL **: pt_waveviewer_set_wave: assertion 'PT_IS_WAVEVIEWER (self)' failed

(parlatype:15194): Gtk-CRITICAL **: gtk_widget_set_sensitive: assertion 'GTK_IS_WIDGET (widget)' failed

(parlatype:15194): Gtk-CRITICAL **: gtk_widget_set_sensitive: assertion 'GTK_IS_WIDGET (widget)' failed

(parlatype:15194): Gtk-CRITICAL **: gtk_widget_set_sensitive: assertion 'GTK_IS_WIDGET (widget)' failed

(parlatype:15194): Gtk-CRITICAL **: gtk_widget_set_sensitive: assertion 'GTK_IS_WIDGET (widget)' failed

(parlatype:15194): Gtk-CRITICAL **: gtk_widget_set_sensitive: assertion 'GTK_IS_WIDGET (widget)' failed

(parlatype:15194): Gtk-CRITICAL **: gtk_label_set_text: assertion 'GTK_IS_LABEL (label)' failed

(parlatype:15194): Gtk-CRITICAL **: gtk_widget_set_tooltip_text: assertion 'GTK_IS_WIDGET (widget)' failed

(parlatype:15194): Gtk-CRITICAL **: gtk_widget_set_tooltip_text: assertion 'GTK_IS_WIDGET (widget)' failed

** (parlatype:15194): CRITICAL **: pt_waveviewer_set_wave: assertion 'PT_IS_WAVEVIEWER (self)' failed

(parlatype:15194): Gtk-CRITICAL **: gtk_widget_set_sensitive: assertion 'GTK_IS_WIDGET (widget)' failed

(parlatype:15194): Gtk-CRITICAL **: gtk_widget_set_sensitive: assertion 'GTK_IS_WIDGET (widget)' failed

(parlatype:15194): Gtk-CRITICAL **: gtk_widget_set_sensitive: assertion 'GTK_IS_WIDGET (widget)' failed

(parlatype:15194): Gtk-CRITICAL **: gtk_widget_set_sensitive: assertion 'GTK_IS_WIDGET (widget)' failed

(parlatype:15194): Gtk-CRITICAL **: gtk_widget_set_sensitive: assertion 'GTK_IS_WIDGET (widget)' failed

(parlatype:15194): Gtk-CRITICAL **: gtk_widget_set_tooltip_text: assertion 'GTK_IS_WIDGET (widget)' failed

(parlatype:15194): Gtk-CRITICAL **: gtk_widget_set_tooltip_text: assertion 'GTK_IS_WIDGET (widget)' failed

** (parlatype:15194): CRITICAL **: pt_waveviewer_set_follow_cursor: assertion 'PT_IS_WAVEVIEWER (self)' failed

** (parlatype:15194): CRITICAL **: pt_waveviewer_set_wave: assertion 'PT_IS_WAVEVIEWER (self)' failed

(parlatype:15194): Gtk-CRITICAL **: gtk_widget_add_tick_callback: assertion 'GTK_IS_WIDGET (widget)' failed

**Comment by mart1oeil** [comment]
I've got the same problem when I install it via Git.

**Comment by gkarsay** [comment]
Thanks for your report! Either something went wrong during upgrade or v1.5.4 is generally not working on your system. When you installed Parlatype the first time, was that already on Ubuntu 17.10 or was it an earlier version? Let's see, if we can get it running at all from a fresh installation.

Before installing from git, you should have uninstalled the package. If you haven't done that yet, please
```sudo apt purge parlatype libparlatype1```

Also uninstall in your git checkout with `sudo make uninstall`. Please make sure there are no traces left, e.g. with `sudo updatedb` followed by `locate parlatype`. There should be no binary left anymore. Then please install it either via PPA or from git. I hope it's working then or at least we'll see if it's an upgrade problem or something else.

**Comment by mart1oeil** [comment]
Great ! That worked.

So thank you for this help and this great tool!
