### ISSUE TITLE
Update PPA to support Ubuntu 18.04 (Bionic)

### ISSUE THREAD

**Issue by fcastilloec** [gkarsay/parlatype#35]
I want to start by saying that I love your app and I don't know what I would do without it, it has saved me so many long hours of work!
Recently, I updated to Ubuntu 18.04. I've been installing your app using the official PPA at https://launchpad.net/~gabor-karsay/+archive/ubuntu/parlatype but there's no repository for Bionic.
For a workaround, I had to manually edit the source file so it pulls the package for Artful, but I would love to see the PPA updated to include the latest version of Ubuntu.

Thanks again!

**Comment by gkarsay** [comment]
Ubuntu 18.04 is the first Ubuntu version to have Parlatype out of the box in its repositories. The shipped version is 1.5.4 (see https://packages.ubuntu.com/search?keywords=parlatype&searchon=names&exact=1&suite=bionic&section=all). Currently this is the latest version. As soon as there will be a new version, I will add it to the PPA.

**Comment by gkarsay** [comment]
There's a new version 1.5.6 in the PPA for Ubuntu 18.04, 16.04 and 14.04. The PPA will be only for LTS versions from now on.
