### ISSUE TITLE
statistics

### ISSUE THREAD

**Issue by qwertygc** [gkarsay/parlatype#36]
Hello,
i propose a issue to add a enhancement to Parlatype. The software Sonal have a statistics fonction. Just calcul a ratio between the time of audio channel and the time than we use to retranscribe. In my opinion, it's a good enhance pour have the motivation to retranscribe, like a challenge.

**Comment by gkarsay** [comment]
Thank you for your suggestion, qwertygc! I'm afraid, I will not implement this, let me explain why:

The actual typing process is not in Parlatype, but in e.g. LibreOffice or whatever you like. That means Parlatype doesn't know, when you start or when you end transcribing. It would need a Start/Stop button which would be a bit confusing next to the Play/Pause button.

I see two possible benefits of such a statistics function: As you say, it's a motivation and challenge, the buzzword i think is gamification. However, this is not a program to learn transcribing, where you would expect such a feature.

It might be also interesting for professionals who are paid per time spent, but i think that there a better tools for them to manage their working times.

Let me be honest: I don't think this is very useful and my resources are limited. I know that other projects would keep such an issue open forever without doing anything. I prefer to close it to make it clear that I don't have the time to implement this.
