### ISSUE TITLE
Custom timestamps

### ISSUE THREAD

**Issue by atmarsden95** [gkarsay/parlatype#37]
This is a feature request, rather than an issue report.

I use Parlatype semi-professionally as a transcriber, and it works great for me, but the timestamp format is a bit of a hassle.

Pretty much all clients and jobs I've had have required formatting of timestamps is '(hh:mm:ss)' format, or '(hh.mm.ss)' format, always including leading zeroes, which is a pain to convert using regexes after typing. (Though not impossible). (Sometimes the parentheses are not required in my work, but that's much less of an issue to rectify.) Options to always exclude fractional seconds and to include all 6 places of precision would be appreciated

The other major feature that isn't implemented is timecode offsets, which is especially a thing when working with recorded video media productions - my files are often coded with the absolute time of day, rather than the time into the file. An option to set the start of the file as, say, 15:06:34, rather than 00:00:00 (by adding 15h06m34s to the timecode throughout) would be massively helpful, but I understand this one is more work than the custom timestamp formats.

**Comment by gkarsay** [comment]
Thanks for your suggestions! They look both interesting and I might consider them for the 1.6 release (there will be 1.5.5 before). Could you please open a separate issue for the second suggestion and copy & paste the last paragraph there?

**Comment by BWPanda** [comment]
I'd also like the ability to customise the timestamp format.
