### ISSUE TITLE
Patch to open new files from the directory last used

### ISSUE THREAD

**Issue by telemann** [gkarsay/parlatype#43]
[last.txt](https://github.com/gkarsay/parlatype/files/2312094/last.txt)

**Comment by gkarsay** [comment]
Thank you! I like the idea and it works. However, memory profiling tools like Valgrind will probably report a memory leak (`gtk_file_chooser_get_current_folder()` has to be freed). I will look into that and maybe I will decide for a different implementation of the idea.

**Comment by gkarsay** [comment]
The referenced commit does the same thing, just a different solution. Works also if the last file was opened via command line or drag'n'drop.
