### ISSUE TITLE
tarball verification

### ISSUE THREAD

**Issue by jubalh** [gkarsay/parlatype#44]
It is nice that you provide an `.asc` file so we can check the tarball.
Would you mind stating on the website or somewhere else which key we should check against?

**Comment by gkarsay** [comment]
Thanks for the suggestion, I have created and added a link in the releases/download section to https://gkarsay.github.io/parlatype/signed.html

**Comment by jubalh** [comment]
Very nice, thanks @gkarsay !

**Comment by jubalh** [comment]
BTW:
Regarding https://gkarsay.github.io/parlatype/installation.html

parlatype is in the openSUSE devel project `utilities`.
Users of openSUSE Leap 15.0 can add this repo by:

```
zypper ar -f obs://utilities utilities
zypper ref
zypper in parlatype
```

And parlatype is also on it's way to the official repository of openSUSE Tumbleweed with [this request](https://build.opensuse.org/request/show/631758).

**Comment by jubalh** [comment]
> I see in your changelog/spec file you don't install the desktop file because you get a non valid error. What's wrong with it?

Thanks for the hint. Actually this got solved with:
https://github.com/gkarsay/parlatype/commit/eb284ad60186a66f00a42d9eabcd321bf9c33b11

Changed the spec file.
