### ISSUE TITLE
Waveform invisible when window focused

### ISSUE THREAD

**Issue by ferdnyc** [gkarsay/parlatype#5]
I tried building and installing Parlatype under Fedora 25, pretty stock Gnome Shell with standard Adwaita theme, using the 1.5 release tarball. There seems to be a problem with styling for the waveform. When the window is focused, it's invisible:

![screenshot from 2017-06-26 07-37-58](https://user-images.githubusercontent.com/538020/27537665-d117dde0-5a42-11e7-9bdd-ee409cf5669b.png)

The waveform only becomes visible when the window loses focus:

![screenshot from 2017-06-26 07-37-47](https://user-images.githubusercontent.com/538020/27537706-fa8c32de-5a42-11e7-9365-102ab701bd68.png)

It appears that commit abf2d5e may be at least partly to blame; I rolled a patch that reverted that commit, and applied it before building. That made the waveform visible when focused, and Parlatype was usable:

![screenshot from 2017-06-26 07-36-53](https://user-images.githubusercontent.com/538020/27537782-43430fb6-5a43-11e7-8b3d-4ef0c76539bd.png)

**Comment by ferdnyc** [comment]
Huh. Curiouser and curiouser. I just discovered, purely by accident, that the waveform display becomes visible if the Parlatype window is enlarged. (I initially thought the problem had cleared up, possibly due to a recent reboot, and I was going to have to retract this bug report. But, no, it's all dependent on the window size. The following three screenshots are from the exact same _instance_ of Parlatype (same file loaded, selection and cursor in the same spot), the only difference is the window dimensions and/or focus at the time each was taken:

![screenshot from 2017-06-27 10-13-34](https://user-images.githubusercontent.com/538020/27594588-29984406-5b28-11e7-94b3-7106ff7bfe1b.png)


![screenshot from 2017-06-27 10-13-46](https://user-images.githubusercontent.com/538020/27594596-2e9e41da-5b28-11e7-8cc6-198f5b19062f.png)


![screenshot from 2017-06-27 10-14-01](https://user-images.githubusercontent.com/538020/27594599-31e6c1d2-5b28-11e7-9879-7e5cc0a55937.png)

**Comment by ferdnyc** [comment]
It seems the effect mentioned in my previous comment is entirely dependent on the window _width_, and the waveform is only visible when the window is enlarged to fit the *entire* waveform. If I load a longer clip, one that can't fit entirely within the window, then there is no size at which it becomes visible.

**Comment by gkarsay** [comment]
Thank you for bug report! I haven't seen this behaviour before and can't reproduce it now.
Fedora 25 means you have Gtk+ 3.22 with Wayland? Is there any error output on the console? 

Could you please build it from git master? The artifacts should be solved with commit 1363fb554fec532bdc3b2ba21216f92832938afc. Parts of the code regarding colors were changed since version 1.5 and I plan to release it as 1.5.1 soon.

Do you have this with Wayland as well as X-Server? Is it the same if you run it with `GTK_THEME=Adwaita:dark parlatype`?

**Comment by ferdnyc** [comment]
No Wayland here, actually, as I'm using NVidia proprietary drivers. So, it's strictly an Xorg-only install of 3.22. (Specifically, at the moment, `gtk3-3.22.15` and `gnome-shell-3.22.3`.)

`GTK_THEME=Adwaita:dark` _does_ appear to solve the problem (though the graphical corruption past the end of a short waveform is still there, in inverse colors), so that appears to be a workaround.

I'll roll up a build of the git HEAD later today, and report back on the results there. Thanks!

**Comment by ferdnyc** [comment]
There isn't any stdout/stderr output, when run from the command line, but the user journal does pick up a few things:

```
% journalctl --no-hostname --user -e _COMM=parlatype -o short |cat
Jun 27 13:54:19 parlatype[14387]: gtk_widget_queue_draw_area: assertion 'height >= 0' failed
Jun 27 13:54:19 parlatype[14387]: gtk_widget_queue_draw_area: assertion 'height >= 0' failed
Jun 27 13:54:30 parlatype[14387]: g_cclosure_marshal_VOID__POINTER: assertion 'n_param_values == 2' failed
```

**Comment by ferdnyc** [comment]
Exact same visibility situation with a build from git HEAD (commit 49f5b6f0), though the corruption is indeed cleared up: Waveform is invisible unless the window is unfocused, becomes visible when the window is resized larger than the entire waveform, `GTK_THEME=Adwaita:dark` is useful as a workaround.

Actually, I noticed this time around that even _with_ the dark theme, the waveform background changes color when the window is resized larger than the waveform. (See the last two screenshots.) So, that may be a clue as to what's going on in the light theme, as well.

![screenshot from 2017-06-27 14-30-31](https://user-images.githubusercontent.com/538020/27603954-dc8f49f2-5b45-11e7-9acf-6a45b284a4f4.png)
![screenshot from 2017-06-27 14-30-38](https://user-images.githubusercontent.com/538020/27603955-dc8f925e-5b45-11e7-9bab-c8b2f6ed3924.png)
![screenshot from 2017-06-27 14-30-50](https://user-images.githubusercontent.com/538020/27603956-dc90f32e-5b45-11e7-977d-0dbce897d28f.png)
![screenshot from 2017-06-27 14-31-40](https://user-images.githubusercontent.com/538020/27603957-dc94e9e8-5b45-11e7-80af-8d1b9a212a79.png)
![screenshot from 2017-06-27 14-31-48](https://user-images.githubusercontent.com/538020/27603953-dc8f3930-5b45-11e7-9114-d79d76050527.png)

**Comment by gkarsay** [comment]
I believe the bug is fixed now, please reopen it if you still experience this problem.

In Gtk+ 3.18, where I tested Parlatype last time, the background was rendered automatically. In Gtk+ 3.22, maybe already in 3.20, obviously the widget has to render the background itself. If it doesn't render the background, the background is black, with Adwaita light theme the waveform is black, too, hence invisible.

**Comment by ferdnyc** [comment]
Did a git pull and started building the moment I saw the close notification. 👍 I can confirm that this is fixed: the waveform now renders properly as black-on-white using the standard Adwaita (light) theme, at any window size. Looks good, thanks!
