### ISSUE TITLE
Fedora dependencies

### ISSUE THREAD

**Issue by birdsarah** [gkarsay/parlatype#50]
To build on Fedora, I needed the following dependencies, which are worded slightly differently than what's in the README:

* gstreamer1-plugins-base-devel
* gstreamer1-devel
* gtk3-devel
* gtk-doc (note there is no gtk-doc-tools on fedora)
* gobject-instrospection-devel

I think that was all of it.

**Comment by gkarsay** [comment]
I added a package list in the referenced commit, I did not test though on Fedora.
