### ISSUE TITLE
Appstream data not correctly displayed

### ISSUE THREAD

**Issue by baimafeima** [gkarsay/parlatype#51]
Parlatype doesn't appear as a regular entry in the Solus Software Center. I've raised the issue downstream here: https://dev.getsol.us/T5199 and it appears that this is an upstream problem of how appstream data is generated. It would be great if you could look into it as currently the app cannot be found by other Solus users and it would be great to have more exposure to such a great program. I've also attached a screenshot below. 
![parlatype](https://user-images.githubusercontent.com/23112309/46488003-c165d900-c801-11e8-81a1-6455bd6eac75.png)

**Comment by gkarsay** [comment]
This has to be solved downstream, I added a comment to the downstream issue.

**Comment by baimafeima** [comment]
Thanks, very much appreciated.
