### ISSUE TITLE
LibreOffice helpers not working

### ISSUE THREAD

**Issue by steelstrings** [gkarsay/parlatype#53]
### Installation and version

How did you install Parlatype?

* ArchLinux AUR tarball
https://aur.archlinux.org/packages/parlatype/
`parlatype --version` 1.5.6
I changed the configure line in the PKGBUILD to enable LibreOffice helpers
`./configure --prefix=/usr --with-libreoffice --disable-introspection --disable-tests`

### Your desktop environment

* Distro: Manjaro Linux
* WM: i3
* LibreOffice: v6.0.6.2

### Issue

* LibreOffice helpers don't work / produce an error
* I never tried previous versions of Parlatype
* Steps to reproduce:
I made a toolbar for all Parlatype LibreOffice Macros, if I click on the `PlayPause` button an error window pops up
```
com.sun.star.uno.RuntimeException: Error during invoking function PlayPause in module file:///usr/lib/libreoffice/share/Scripts/python/Parlatype.py (<class 'TypeError'>: PlayPause() takes 0 positional arguments but 1 was given
  File "/usr/lib/libreoffice/program/pythonscript.py", line 875, in invoke
    ret = self.func( *args )
)
```
* Keyboard shortcuts don't work either and they don't show any error message.
* Every macro gives a similar error, only the function changes accordingly.

**Comment by gkarsay** [comment]
Thank you for the detailed bug report! I repeated your steps and I have to confirm that it's not working with buttons. I always used keyboard shortcuts and was not aware that with buttons obviously something has to be done in a different way.

I can't confirm however that keyboard shortcuts are not working. Could you please try this part again? In the help pages you'll find instructions, please do it as described there: https://gkarsay.github.io/parlatype/help-online/libreoffice-helpers.html

I just found out that it's possible to close the dialog (2nd screenshot in link above) without clicking on "OK". You have to assign a shortcut to a function AND you have to click on OK! Parlatype has to be open with a file opened.

**Comment by gkarsay** [comment]
The referenced commit has fixed the issue with buttons. Please reopen it, if you still have some issues with it. You can download the fixed libreoffice macros here: https://raw.githubusercontent.com/gkarsay/parlatype/master/libreoffice/Parlatype.py and save them at /usr/lib/libreoffice/share/Scripts/python/Parlatype.py
