### ISSUE TITLE
install instructions fail

### ISSUE THREAD

**Issue by OSaaa** [gkarsay/parlatype#54]
### Installation and version

How did you install Parlatype?

* From git? If yes, please paste the output of `git log -1 --pretty=oneline`
$ git log -1 --pretty=oneline
7c3bd275396fbed542cb38ee747520c20f8dc6b9 [window] remove non-functional drag'n'drop from time label

* From tarball? If yes, please paste the output of `parlatype --version`

* From a distro package?
Please add information about that package, like the version or where you got it from.

### Your desktop environment

* What's your distro? (name and version, if applicable)

Debian GNU/Linux 9.5 (stretch)

* What's your desktop environment? (GNOME, KDE, XFCE ...)

GNOME

* If it's about LibreOffice helpers: What's your LibreOffice version?

### Issue

* What is not working as expected?

//Per https://github.com/gkarsay/parlatype/
//instructions to install were:
On a Debian based distro you can install all these (dependencies) with:
$ sudo apt-get install build-essential automake autoconf intltool libgirepository1.0-dev libgladeui-dev gtk-doc-tools yelp-tools libgtk-3-dev libgtk-3-0 libgstreamer1.0-dev libgstreamer1.0-0 libgstreamer-plugins-base1.0-dev gstreamer1.0-plugins-good gstreamer1.0-plugins-ugly libreoffice-script-provider-python
//done, no errors reported
//from install instructions:
Clone the repository and run autogen.sh. Assuming you want the program only:

$ git clone https://github.com/gkarsay/parlatype.git
$ cd parlatype
$ ./autogen.sh --prefix=/usr --disable-introspection
//done, no errors reported

$ make
//failed
Makefile:620: recipe for target 'pt-progress-dialog.lo' failed
make[5]: *** [pt-progress-dialog.lo] Error 1
make[5]: Leaving directory '/home/owner/Downloads/parlatype/libparlatype/src'
Makefile:514: recipe for target 'all' failed
make[4]: *** [all] Error 2
make[4]: Leaving directory '/home/owner/Downloads/parlatype/libparlatype/src'
Makefile:500: recipe for target 'all-recursive' failed
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory '/home/owner/Downloads/parlatype/libparlatype'
Makefile:432: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/home/owner/Downloads/parlatype/libparlatype'
Makefile:473: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/owner/Downloads/parlatype'
Makefile:405: recipe for target 'all' failed
make: *** [all] Error 2

//tried
$sudo make
//same errors

* Does it happen all the time?
//yes
* Did it work in the past (a regression)?
//no, this is as far as I got.
* What steps are needed to reproduce it?
//See above 
* If you start Parlatype from terminal, is there any error output?
$ parlatype
bash: parlatype: command not found

### Other information

Please add any other information that might be useful.

For example if there is a problem with the display of the waveform, which theme do you use?
Maybe a screenshot can illustrate the problem.

**Comment by gkarsay** [comment]
Thank you for the detailed bug report! I can't reproduce this on Debian stable, did you install also the dependencies as described in README.md in Installation > Dependencies > Master?
The command is:
```
sudo apt install autoconf-archive appstream-util
```
Does it work then?

**Comment by gkarsay** [comment]
Closing this because there was no response and it's obsolete: Master branch switched to Meson instead of Autotools.
