### ISSUE TITLE
Workflow mouse focused

### ISSUE THREAD

**Issue by haevalencia** [gkarsay/parlatype#56]
### Installation and version

How did you install Parlatype?

* From flathub (1.5.6)

### Your desktop environment

* What's your distro?
Fedora 28
* What's your desktop environment?
GNOME and KDE

### Improvement

Usually the software available for manual transcription of spoken language is more technical, focused on a knowledgeable user who prefers keyboard shortcuts, however, it is common for not so advanced users to use this type of software.

Based on the working of an old software with the same purpose for windows, it occurred to me that maybe, Parlatype had an automatic playback/pause function when moving the cursor over the app window. In this way, a user could keep the window of Parlatype in a place not annoying on a processor/text editor and just pass the cursor to play and go quickly to the other window to continue writing without keyboard shortcuts and fewer clicks.
Technically I don't know if it is possible, but another option is automatic playback/pause when you gain windows focus, so something like focusing the window with Alt + TAB would play automatically, gaining time for the user.

**Comment by gkarsay** [comment]
Thanks for your suggestions and sorry for the late reply! While this would be probably technically possible, I think it's against all expectations of an average user. Hovering with a pointer over an interface or a window's focus change never trigger an action. As far as I can see this case is not mentioned in the [GNOME Human Interface Guidelines](https://developer.gnome.org/hig/stable/) but I would say they just didn't think of this possibility.

Thank you for sharing your thoughts but for the given reasons I won't implement these suggestions.
