### ISSUE TITLE
Parlatype doesnt play sound file

### ISSUE THREAD

**Issue by JLuc** [gkarsay/parlatype#57]
I installed Parlatype a long time ago and it has been worked efficiently several times. 
Now It's parlatype 1.5.4-1 on Ubuntu 18.04 

Now, it wont play the opened .m4a file.
When i click "Play", nothing happen.
When i launch it from terminal, there is no log.

By chance, I found a workaround : 
- Menu "Go to..."
- Click on "+" button -> 0.01 second
- Play

It plays now ! And i can stop and go and go back to 0 and play...

**Comment by gkarsay** [comment]
Thank you for your bug report! Did you install from my PPA? The newest version is 1.5.6, although this should not make a difference for this bug.

Does it happen with every .m4a file?
If it happens only for a specific .m4a file: Does it happen every time you open it?
If it's a specific file, is it confidential? Could you send it to me via email? My email is in the copyright statement of the source code, e.g. in https://github.com/gkarsay/parlatype/blob/master/src/pt-window.c
