### ISSUE TITLE
Can't set preferences

### ISSUE THREAD

**Issue by tespro** [gkarsay/parlatype#65]
### Installation and version
I'm actually not sure what version I'm running because I use Ubuntu 18.04 and I'm assuming it keeps your program updated along with everything else. I've had parlatype running for a year or so. I don't see any version number displayed anywhere. Am I missing something?

### Your desktop environment

Gnome

### Issue
I can't set the preferences as shown in the help documentation.
* Does it happen all the time? Yes
* Did it work in the past (a regression)? No
* If you start Parlatype from terminal, is there any error output? No - and I can run it from both the desktop and terminal. Works the same in both circumstances.

**Comment by gkarsay** [comment]
Do you mean you don't know where to set the preferences? You have probably version 1.5.4. Preferences are like for most GNOME applications in the so called Application menu, which is in the upper left corner next to "Activities":
![Parlatype-Preferences-v1 5 x](https://user-images.githubusercontent.com/8670449/64272115-f4977780-cf3e-11e9-8db4-e90e277ebd49.png)
There is also a menu item "Info" that shows the version of Parlatype. Note that this changed with version 1.6 and now the Preferences are found in the "Hamburger" menu.

I hope this helps! If finding the Preferences was not the problem, please describe in detail what is not working.

**Comment by tespro** [comment]
Thanks so much for your very prompt reply. I can't remember anymore what I
may have done when I first installed this program but, for now, all I have
when I run the program is the box inside the yellow box in your e-mail that
has the open icon, speed control, etc. There is nothing that I can find in
the menu in that box that would give me what exists in the yellow box or
would take me back to the expanded screen.

I down-loaded your software when I first started thinking about switching
my English teaching program from Windows to Linux. I want to start a free
community service here in rural Florida to teach people to read and/or
learn English. There are a lot of poor Americans here - some of whom can
barely read if at all. (We've had a collapse of the oyster economy that
provided good incomes for decades.) Immigrants need to use a transcription
program to practice listening to spoken English. I'd first tried teaching
English to a relatives and used a Windows program called Listen- 'N-
Write.  I've had some good success and my sister-in-law, for example, has
made great progress after doing this for more than a year. Yours has been
the best Linux program I've found (keeping in mind that I'm doing this for
poor people here for free) and my plan is to use mousepad as the editor.
I'm trying to keep the user interface as simple as possible. Most of my
program is character-based like the old DOS era. I have written the drill
program which is where the students will spend most of their time. There is
NO WAY I want to try to teach the near-illiterate how to use Windows 10!!!

That's the background as to why I've suddenly started to learn everything I
can about Parlatype and discovered I couldn't do what I read online.

Thanks again.

Tom Stover
Eastpoint, FL

**Comment by gkarsay** [comment]
The yellow thing you see in the picture is just my desktop with a sunset in the background. I'm not sure what your desktop looks like, you said it's the GNOME desktop. There should be a panel or bar on top and on the very left there is the word "Activities". Do you have that? If not, you are using another desktop, maybe Xfce? When you launch Parlatype, next to "Activities" appears "Parlatype". You can click on this "Parlatype" and you get this menu. Many programs have there some menus, others only a "Quit" item. So you don't click on the Parlatype window/box, but where the word "Parlatype" appears on the top bar next to "Activities".

There is also a "Help" item. You can launch "Help" also by pressing the `F1` key. Please note the help pages you can find on the Internet are describing a different version of Parlatype. When you hit the `F1` key you get help for the version you have installed on your computer.

If this didn't help, can you make a screenshot of your desktop with Parlatype running?

**Comment by tespro** [comment]
I've got the standard desktop that was installed when I upgraded to Ubuntu
18.04 from, I believe, 17.10. I do not have the desktop appearance that you
describe.   GNOME replaced Unity. When I say I clicked the applications
menu, on GNOME there are 9 dots at the lower left of the screen. That's
what brings up icons for all the apps; I usually have it set for installed
apps only.


Here's what shows up when I click the applications icon:
[image: P2.JPG]

Here is what shows up when I click that parlatype icon OR if I run
parlatype directly from terminal:

[image: Screenshot from 2019-09-03-Parlatype.png]

I hope this gives you a clue. Thanks. Tom

**Comment by gkarsay** [comment]
I can't see the screenshots. Please use the web interface where you have reported the issue, not email. Drag & drop the screenshots at a new comment.

**Comment by tespro** [comment]
![image](https://user-images.githubusercontent.com/54864350/64344112-d0c64700-cfbb-11e9-9db5-a3215b8c201a.png)
![image](https://user-images.githubusercontent.com/54864350/64344327-3c101900-cfbc-11e9-986a-77a1462d6188.png)

Did this work?

**Comment by gkarsay** [comment]
Well, this worked. However, I hoped to see a bit more to identify the desktop. I'm attaching a screenshot of the whole desktop. This is what a GNOME desktop usually looks like – more or less, of course there can be some minor differences, e.g. the language is different.

![Parlatype-GNOME-full](https://user-images.githubusercontent.com/8670449/64349909-10128900-cff8-11e9-9355-75217acf1627.png)

In the upper left corner there is Activities and next to it – I marked it in red – is the place with the application's menu where you can click on. It's showing the name of the program in the foreground. Do you have that? If no, you might have some Addon that is disabling the top panel (I rather don't think so) or you have a different desktop. Unity desktop is still present in Ubuntu 18.04, it's just not the standard desktop. You mentioned 9 dots to show all applications, that's a hint for GNOME actually.

**Comment by tespro** [comment]
Hey, you gave me the right clue!! I needed to close all the other
applications that were running and then I saw "Parlatype" right next to
activities. NOW I can see how to set the preferences. Sorry for being
behind the curve on Linux!! You've been very patient with me and stuck it
out to the solution!! Thanks again. Tom
