### ISSUE TITLE
GLib-GIO-ERROR Settings schema 'com.github.gkarsay.parlatype' is not installed

### ISSUE THREAD

**Issue by noregrof** [gkarsay/parlatype#67]
Hi,

Installed parlatype from git on a debian buster (10/stable) with  starting command
meson build --prefix=/usr/local/lib/parlatype

Got every thing compiled and installed but running (as suggest from the meson build) :
user:~/$ LD_LIBRARY_PATH=/usr/local/lib/parlatype/lib/x86_64-linux-gnu:/usr/local/lib/sphinx/lib GST_PLUGIN_PATH=/usr/local/lib/parlatype/lib/x86_64-linux-gnu/gstreamer-1.0 /usr/local/lib/parlatype/bin/parlatype

got me this error
(parlatype:3754): GLib-GIO-ERROR **: 17:13:20.303: Settings schema 'com.github.gkarsay.parlatype' is not installed
Trace/breakpoint trap

After digging a bit to understand how setting schema are working, found out that
data/com.github.gkarsay.parlatype.gschema.xml 
had not been installed to /usr/share/glib-2.0/schemas as expected by the system
but obviously installed in /usr/local/lib/parlatype/share/glib-2.0/schemas.

So I just added 
XDG_DATA_DIRS=$XDG_DATA_DIRS:/usr/local/lib/parlatype/share
to the previous command line :
user:~/$ LD_LIBRARY_PATH=/usr/local/lib/parlatype/lib/x86_64-linux-gnu:/usr/local/lib/sphinx/lib XDG_DATA_DIRS=$XDG_DATA_DIRS:/usr/local/lib/parlatype/share GST_PLUGIN_PATH=/usr/local/lib/parlatype/lib/x86_64-linux-gnu/gstreamer-1.0 /usr/local/lib/parlatype/bin/parlatype

Maybe this was trivial, but I suggest that in case someone use a --prefix in the meson command that you add the XDG_DATA_DIRS=$XDG_DATA_DIRS:${PREFIX} to the command line shown

Many thanks for this great work,
Best wishes,
Fred.

**Comment by gkarsay** [comment]
Thank you!
