### ISSUE TITLE
Failed to load plugin: "parlasphinx"

### ISSUE THREAD

**Issue by axelmeunier** [gkarsay/parlatype#69]
### Installation and version

How did you install Parlatype?
version 1.6.1-3 from Ubuntu software 

### Your desktop environment
Ubuntu 19.10 Gnome DE
### Issue

* What is not working as expected?
Parlatype crashes on launch with error message:
"Parlatype needs GStreamer 1.x to run. Please check your installation of GStreamer and make sure you have the "Good Plugins" installed. Parlatype will quit now, it received this error message: Failed to load plugin "parlasphinx". 

* Does it happen all the time?
yes

* Did it work in the past (a regression)?
used to work last time I installed (probably more than a year back, so it was not on the same distro.

* What steps are needed to reproduce it?
Install Parlatype from Ubuntu Software or by terminal (sudo apt install parlatype).
Launch.

* If you start Parlatype from terminal, is there any error output
No

### Other information
I tried to install libsphinxbase-dev and libpocketsphinx-dev.
It did not solve the problem.

**Comment by gkarsay** [comment]
You mentioned in another bug report the Flathub version. Please make sure, you have only one version of Parlatype installed. In case you have built it from source before, make sure there are no traces left from that version. Do you still have the problem then?

**Comment by axelmeunier** [comment]
Ok so maybe that was the problem, I installed successively the flatpak then the deb version without checking that everything was removed from the 1st. I can't say I did not check because I realised the flatpak did not have any bug. So I will close this issue for now.
