### ISSUE TITLE
Failed to load plugin "Parlasphinx"

### ISSUE THREAD

**Issue by CristianCrispini** [gkarsay/parlatype#74]
### Installation and version
Installed from tarball.

cristian@HP-pavillon:~$ parlatype --version
parlatype 2.0

### Your desktop environment

* What's your distro? Ubuntu 20.04
* What's your desktop environment? Gnome

### Issue

* What is not working as expected?
**Failed to load plugin parlasphinx**
* Does it happen all the time?
**yes**
* Did it work in the past (a regression)?
**Not in this version. I've correctly installed on previous version**
* What steps are needed to reproduce it?
**just installed using the readme.md instruction. after ninja installed the software i've started it.**
* If you start Parlatype from terminal, is there any error output?
**Yes**

> Parlatype needs GStreamer 1.x to run. Please check your nstallation of GStremer and make sure youhave the "Good Plugins" intalled. Parlatype will quit now, it received this error message: Failed to load plugin "parlasphinx"

### Other information

> cristian@HP-pavillon:~$ dpkg -l | grep gstreamer

ii  gir1.2-gstreamer-1.0:amd64                 1.16.2-2                              amd64        GObject introspection data for the GStreamer library

ii  gstreamer1.0-alsa:amd64                    1.16.2-4                              amd64        GStreamer plugin for ALSA

ii  gstreamer1.0-clutter-3.0:amd64             3.0.27-1                              amd64        Clutter PLugin for GStreamer 1.0

ii  gstreamer1.0-doc                           1.16.2-2                              all          GStreamer core documentation and manuals

ii  gstreamer1.0-gl:amd64                      1.16.2-4                              amd64        GStreamer plugins for GL

ii  gstreamer1.0-gtk3:amd64                    1.16.2-1ubuntu2                       amd64        GStreamer plugin for GTK+3

ii  gstreamer1.0-libav:amd64                   1.16.2-2                              amd64        ffmpeg plugin for GStreamer

ii  gstreamer1.0-packagekit                    1.1.13-2ubuntu1                       amd64        GStreamer plugin to install codecs using PackageKit

ii  gstreamer1.0-plugins-bad:amd64             1.16.2-2.1ubuntu1                     amd64        GStreamer plugins from the "bad" set

ii  gstreamer1.0-plugins-base:amd64            1.16.2-4                              amd64        GStreamer plugins from the "base" set

ii  gstreamer1.0-plugins-base-apps             1.16.2-4                              amd64        GStreamer helper programs from the "base" set

ii  gstreamer1.0-plugins-good:amd64            1.16.2-1ubuntu2                       amd64        GStreamer plugins from the "good" set

ii  gstreamer1.0-plugins-ugly:amd64            1.16.2-2build1                        amd64        GStreamer plugins from the "ugly" set

ii  gstreamer1.0-pulseaudio:amd64              1.16.2-1ubuntu2                       amd64        GStreamer plugin for PulseAudio

ii  gstreamer1.0-qt5:amd64                     1.16.2-1ubuntu2                       amd64        GStreamer plugin for Qt5

ii  gstreamer1.0-tools                         1.16.2-2                              amd64        Tools for use with GStreamer

ii  gstreamer1.0-vaapi:amd64                   1.16.2-2                              amd64        VA-API plugins for GStreamer

ii  gstreamer1.0-x:amd64                       1.16.2-4                              amd64        GStreamer plugins for X11 and Pango

ii  libgstreamer-gl1.0-0:amd64                 1.16.2-4                              amd64        GStreamer GL libraries

ii  libgstreamer-plugins-bad1.0-0:amd64        1.16.2-2.1ubuntu1                     amd64        GStreamer libraries from the "bad" set

ii  libgstreamer-plugins-base1.0-0:amd64       1.16.2-4                              amd64        GStreamer libraries from the "base" set

ii  libgstreamer-plugins-base1.0-dev:amd64     1.16.2-4                              amd64        GStreamer development files for libraries from the "base" set

ii  libgstreamer-plugins-good1.0-0:amd64       1.16.2-1ubuntu2                       amd64        GStreamer development files for libraries from the "good" set

ii  libgstreamer1.0-0:amd64                    1.16.2-2                              amd64        Core GStreamer libraries and elements

ii  libgstreamer1.0-dev:amd64                  1.16.2-2                              amd64        GStreamer core development files

**Comment by gkarsay** [comment]
Thanks for your bug report! Which prefix did you use for installing Parlatype? In the build directory you can do `meson configure | grep prefix` to get the prefix in use.

**Comment by CristianCrispini** [comment]
cmake_prefix_path       []                                                                                 
T.List of additional prefixes for cmake to search
  build.cmake_prefix_path []                                                                                 
T.List of additional prefixes for cmake to search
  prefix                  /usr/local                                                                        
 Installation prefix

**Comment by CristianCrispini** [comment]
I've started parlatype as sudo users and a warning pop out!

> Failed to load plugin '/usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstparlasphinx.so': /lib/x86_64-linux-gnu/libpocketsphinx.so.3: undefined symbol: err_set_debug_level

Then i've searched if this error had happened previously. I have used journalctl to access the logZ.
Apparently this problem occured just 2 times...

**Comment by gkarsay** [comment]
What command did you use to get the output above? There shouldn't be anything with cmake in the output, Parlatype doesn't use that build system. So I would like to know which prefix you used when installing Parlatype. You can get it if you enter this in a terminal in the build directory (without the $ sign):
```
$ meson configure | grep prefix
```
The output should look something like this, just a single line:
```
  prefix         /usr/local           Installation prefix
```

**Comment by CristianCrispini** [comment]
> cmake_prefix_path []
> T.List of additional prefixes for cmake to search
> build.cmake_prefix_path []
> T.List of additional prefixes for cmake to search
> **prefix /usr/local Installation prefix**

**Comment by gkarsay** [comment]
I'm sorry for answering very very late ...

When installing to a prefix other than `/usr` there are several environment variables that should be adjusted. For GStreamer it is `GST_PLUGIN_PATH`. When building parlatype the first time with a prefix other than `/usr`, it will print the correct command line to invoke parlatype, e.g. for `/usr/local` it is:

```
 Command to run parlatype:
 LD_LIBRARY_PATH=/usr/local/lib/x86_64-linux-gnu GST_PLUGIN_PATH=/usr/local/lib/x86_64-linux-gnu/gstreamer-1.0 XDG_DATA_DIRS=$XDG_DATA_DIRS:/usr/local/share /usr/local/bin/parlatype
```
This line should work on Debian based systems, others might have slightly different paths; just have a look what Meson shows you.

There are other ways to work around this: You can use `/usr` as prefix; that is actually what the README suggests. If you don't want to use the ASR capabilities, you can also turn off ASR at build time with `-Dasr=false` and there should be no problem with the GStreamer plugin anymore.

**Comment by gkarsay** [comment]
As I wrote earlier I think this is a prefix problem.

As of version 3.0 this plugin is compiled into Parlatype's own library and this should eliminate all problems relating to GStreamer trying to find the plugin.
