### ISSUE TITLE
Minor app icon update

### ISSUE THREAD

**Issue by bertob** [gkarsay/parlatype#75]
The current icon is pretty good, but since it was designed for the old gudelines, there are a few minor issues with it. For example, it has a baked-in shadow, which means it ends up having double shadows in GNOME Software, Settings, and other places of the system UI, since icons get automatic shadows in those places now.

I took a quick stab at updating it for the new guidelines:

![image](https://user-images.githubusercontent.com/1908896/86807402-22c37780-c07a-11ea-8363-6e148fc6ba43.png)

If you're interested I can do an MR with the new assets.

**Comment by gkarsay** [comment]
Thank you very much! I will merge it. May I also ask for an extra size? I'm using the icon in the toolbar of my LibreOffice extension. LibreOffice requires it to be 24x24.

**Comment by bertob** [comment]
Cool, I'll make an MR then.

> I'm using the icon in the toolbar of my LibreOffice extension. LibreOffice requires it to be 24x24.

If your current 24px icon already works in that style I'd just keep it as-is for that particular case, the new style would probably not fit in with the LO stuff anyway.

**Comment by bertob** [comment]
I think this can be closed, no?

**Comment by gkarsay** [comment]
Yes, thank you again.
