### ISSUE TITLE
Right-to-left (RTL) layout probably wrong

### ISSUE THREAD

**Issue by gkarsay** [gkarsay/parlatype#77]
I need some informed advice about RTL layout in Parlatype. Please leave a comment, if you have some knowledge how proper RTL layout works.

For comparison, this is how LTR looks like:

![parlatype-ltr](https://user-images.githubusercontent.com/8670449/87693505-5ba3d080-c78d-11ea-9f9c-9a84f1630273.png)

Until recently RTL layout looked like this:

![parlatype-rtl-old-gtk](https://user-images.githubusercontent.com/8670449/87693615-7d9d5300-c78d-11ea-8148-1326f8dfc714.png)

Note that the waveform's ruler, a timeline, is mirrored. It starts at 0:00 on the right and the red cursor moves while playing to the left. The control icons are mirrored, too. On the very right is an icon to jump back in time (pointing to the right), then the Play button and then an icon to jump forward in time (pointing to the left.)

Adwaita icon theme is not mirroring those control icons anymore since https://gitlab.gnome.org/GNOME/adwaita-icon-theme/-/issues/75

Since then Parlatype looks like this:

![parlatype-rtl-newest-gtk](https://user-images.githubusercontent.com/8670449/87694537-9c501980-c78e-11ea-9417-47ffb1d829aa.png)

The icon on the very right is jumping back in time (pointing to the left), then the play button, then an icon to jump forward in time (pointing to the right).

Various sources say that the controls shouldn't be mirrored. Is mirroring the waveform and the timeline also wrong? Do you have any suggestions?

**Comment by ItielMaN** [comment]
As a native RTL language speaker, I'd expect this UI to be the same as in LTR, so the first screenshot should apply also to RTL (maybe except for the top bar- the X button should still be on the left, and the Open button on the right).

**Comment by arashm** [comment]
I'm agreed with Itel.

**Comment by gkarsay** [comment]
Thank you both for your input! I will change it accordingly.
