### ISSUE TITLE
Old runtime warning with flatpak

### ISSUE THREAD

**Issue by elya5** [gkarsay/parlatype#82]
### Installation, version, distro

* How did you install Parlatype? With flatpak  via flathub
* What's your distro? Fedora 34
* What's your desktop environment? GNOME

### Issue

Parlatype uses an old runtime version so there is the following warning:
```
The GNOME 3.36 runtime is no longer supported as of February 13, 2021. Please ask your application developer to migrate to a supported platform.
Applications using this runtime:
   org.parlatype.Parlatype
```

Would it be possible to simply update the runtime in the flatpak manifest?

**Comment by gkarsay** [comment]
Thanks for the reminder, the runtime is now GNOME 40.
