### ISSUE TITLE
Is it possible to use Parlatype with Mozilla's open source speech project?

### ISSUE THREAD

**Issue by LinuxBeaver** [gkarsay/parlatype#83]
Hey, nice software you have. I am just asking if it is possible to configure Parlatype to use Mozilla's open speech project as opposed to just CMUSphinx?

**Comment by gkarsay** [comment]
Currently it's not possible to use Mozilla Deepspeech. I'm working on it since quite a while but it's not ready yet.

**Comment by gkarsay** [comment]
Closing as a duplicate of #71
