### ISSUE TITLE
Implement MPRIS D-Bus Interface Specification

### ISSUE THREAD

**Issue by rcrimp** [gkarsay/parlatype#86]
Installed from [AUR](https://aur.archlinux.org/packages/parlatype/)
Distro: [i3 Manjaro](https://manjaro.org/downloads/community/i3/)
DE/WM: i3wm

Issue: Media keys don't work.

Sending `XF86AudioPlay` works with both VLC and chromium, but not Parlatype.

`$ playerctl play` works with both VLC and chromium but not Parlatype.

Sending messages over dbus doesn't work. I've tried this: 
`$ dbus-send --dest=org.parlatype.Parlatype /org/parlatype/Parlatype org.parlatype.Parlatype.PlayPause`

EDIT:
If I run a Gnome DE (on the same Manjaro machine), Parlatype responds to XF86AudioPlay keys even if the window is inactive =D Though I'd like to get it working on i3 too

**Comment by gkarsay** [comment]
Playerctl uses MPRIS to control players, Parlatype doesn't implement the MPRIS D-Bus Interface Specification.
I would like to have that feature in Parlatype, unfortunately my time is limited and I will probably not implement this (soon or at all). However, if someone with at least basic knowledge in C would like to work on this, I would mentor this person.

**Comment by gkarsay** [comment]
This became more urgent with the announced removal of MediaKeys in favour of MPRIS:
https://www.hadess.net/2021/10/psa-gnome-settings-daemons-mediakeys.html
