### ISSUE TITLE
ASR files are installed even build without ASR

### ISSUE THREAD

**Issue by jubalh** [gkarsay/parlatype#88]
### Installation and version

I'm building the openSUSE distro package for parlatype 3.0.

### Your desktop environment

* openSUSE Tumbleweed
* GNOME

### Issue

I compile with `meson -Ddeepspeech=false -Dpocketsphinx=false`.
And the following files get installed with anyways:

* /usr/share/parlatype/asr/de.deepspeech.skribosermo.asr
* /usr/share/parlatype/asr/de.sphinx.bartsch.voxforge.asr
* /usr/share/parlatype/asr/en.deepspeech.mozilla.0.9.3.asr
* /usr/share/parlatype/asr/en.sphinx.debian.asr
* /usr/share/parlatype/asr/zh_CN.deepspeech.mozilla.0.9.3.asr

If I see it right they should only be installed if ASR is enabled, right?

**Comment by jubalh** [comment]
My guess is that https://github.com/gkarsay/parlatype/blob/main/data/meson.build#L3 should only be done conditionally if with_pocketsphinx or with_deepspeech are set.

**Comment by gkarsay** [comment]
Thank you for your quick bug report!
