### ISSUE TITLE
Change translation license

### ISSUE THREAD

**Issue by comradekingu** [gkarsay/parlatype#89]
BSD-3 is a weak license, and it requires mentioning the license, which complicates matters.
GPLv3-or-later is better since it is already the project license.

**Comment by gkarsay** [comment]
Translations are coming from Launchpad. I have currently a hard time understanding their policy:

> All translations in Launchpad are the work of the translator that created them. Translations of individual strings are made available to Canonical and in turn to you under the BSD license (revised, without advertising clause). […] Translations of groups of strings from the same project, to the extent forming a derivative work of the project, are made available to Canonical and in turn to you under the licence applicable to the project. See the Translations Licensing FAQ for details. 
> -- https://help.launchpad.net/Legal

The FAQ is not adding much information to that:

> We have now updated the "Translations copyright" section of the Launchpad terms of use to require that translations submitted in Launchpad licensed using the BSD licence, but also that groups of strings from one project which are a derivative work of the project are licensed under the licence of the project.
> -- https://help.launchpad.net/Translations/LicensingFAQ

To be on the safe side, I chose in Weblate BSD-3 as license first. Now I'm inclined to think the translations are dual licensed: BSD and project license, in this case GPLv3-or-later.

Do you know of other projects moving from Launchpad and how they solved this? Do you know if the imported .po files are "Translations of groups of strings from the same project, to the extent forming a derivative work of the project"?

**Comment by gkarsay** [comment]
I have changed the license on Weblate to GPLv3-or-later, which is actually what the header of the translations says. The initial license BSD-3 was chosen due to a misunderstanding of the policy of the current translation service provider, Launchpad.

I have requested free hosting on Weblate and now I am hoping and waiting for approval.

**Comment by comradekingu** [comment]
Launchpad required all translations be made BSD something because they didn't have terms and conditions allowing spreading of translations. So translators could either accept re-licensing all their translations, or have them removed.

Effectively it isn't dual-licensed if new contributions are made as GPLv3+.

Since it is GPLv3+ across the board now and it is possible to get there from BSD-something, all is well.
