### ISSUE TITLE
Provide portable version for Linux

### ISSUE THREAD

**Issue by TheAssassin** [gkarsay/parlatype#9]
Please provide a portable version (application bundle) for Linux that can be run without the need to install anything first on the machine, for example an AppImage.

Providing an AppImage would have, among others, these advantages:

- Applications packaged as an AppImage can run on many distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, make it executable, and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Works out of the box, no installation of runtimes needed
- Optional desktop integration with appimaged
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs
- Can use the same AppImages when dual-booting multiple distributions

This will help reaching more potential users, which are not experienced with building software or do not wish to rebuild on every update. And in my experience, many journalists are really grateful for being able to use awesome tools making their life easier without much hassle.

**Comment by gkarsay** [comment]
The idea of a portable distribution is tempting, but I don't have any experience with it yet. There are many solutions, like Flatpak, Snappy, AppImage and I haven't figured out yet, what would be best.

There's one point on AppImage's GitHub site about creating AppImages that makes it a no go for me:

> 5. Test your AppImage on all base operating systems you are targeting. This is an important step which you should not skip. Subtle differences in distributions make this a must. While it is possible in most cases to create AppImages that run on various distributions, this does not come automatically, but requires careful hand-tuning.

**Comment by TheAssassin** [comment]
The step you mention is like the least step in release engineering, and this is nothing AppImage specific.

You cannot skip it with any of the other solutions either, not even traditional software distribution can take that away from you. AppImage, as your everyday friend and helper, is just honest about it and suggests you to do so. None of the other solutions have a solution for this problem, and by following AppImage's suggestion, you're just on the safe side and save yourself from hundreds of bug reports about incompatibilities. That's due to the world we live in, with hundreds of distributions and people running them.

For a public beta, it's totally fine to test it with e.g. Ubuntu or Mint, something popular. Just make sure your application runs the way it should. It's the exact same thing when packaging for good ol' PPAs, you'll have to install the application this way and run it to see if it works.

Just as a side note, the AppImage team is planning to take away at least *some* of the effort required for this with [openQA](http://open.qa/).

**Comment by TheAssassin** [comment]
Any updates to this? Decided whether to create an AppImage yet? If you need help or have general questions, feel free to join the AppImage IRC channel: #AppImage on Freenode. (As usual on IRC, please stay in there for a few hours to give us a chance to see your posting and reply to it.)

**Comment by gkarsay** [comment]
I think I will try Flatpak first, but it's not my top priority at the moment.

**Comment by TheAssassin** [comment]
Well to be honest, Flatpak way less portable, and the point you mentioned negatively doesn't *magically* go away, it has to be done for any kind of distribution.

Could I change your opinion by creating a demo AppImage?

**Comment by gkarsay** [comment]
Thank you, but I don't think I will make it in the near future.

**Comment by TheAssassin** [comment]
Okay. Let me know when you have a Travís (or something else) configuration, then I'll contribute the AppImage builds. I guess they wouldn't hurt even when having Flatpak build configuration.

**Comment by bepolymathe** [comment]
That would be great to have this version. Compilation on Fedora failed for me.

**Comment by gkarsay** [comment]
There's a flatpak package at https://flathub.org/apps.html#Parlatype since a while, so I will close this issue now. I understand you'd rather like an AppImage. You can of course open a new issue explicitly for an AppImage but it would have to be someone else to make and later on maintain it.
